"""servicios

Revision ID: 1439a3ebc413
Revises: f703ae615bdc
Create Date: 2023-02-24 15:56:00.064068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1439a3ebc413'
down_revision = 'f703ae615bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('createdAt',
               existing_type=sa.DATE(),
               type_=sa.Text(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('createdAt',
               existing_type=sa.Text(),
               type_=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
