"""table servicios update

Revision ID: 9cce61f7e0e4
Revises: b6c115e13065
Create Date: 2023-02-24 17:10:42.392564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cce61f7e0e4'
down_revision = 'b6c115e13065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
