"""table servicios

Revision ID: b6c115e13065
Revises: 1439a3ebc413
Create Date: 2023-02-24 16:00:26.044937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c115e13065'
down_revision = '1439a3ebc413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('servicio', sa.String(length=45), nullable=False),
    sa.Column('createdAt', sa.Text(), nullable=True),
    sa.Column('doneAt', sa.Text(), nullable=True),
    sa.Column('deletedAt', sa.Text(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('horario', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_servicios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_servicios')
    op.drop_table('servicios')
    # ### end Alembic commands ###
