"""usuarios updated

Revision ID: f703ae615bdc
Revises: 
Create Date: 2023-02-24 12:56:53.167872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f703ae615bdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('imageProfile', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('lastName', sa.String(length=200), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('tower', sa.Integer(), nullable=False),
    sa.Column('dpto', sa.Integer(), nullable=False),
    sa.Column('condominio', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
